[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "systeml"
version = "0.1.0"
description = "Some functions to work with LLM"
readme = "README.md"
authors = [
    {name = "Paul Khoziashev", email = "79194544428@ya.ru"}
]
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
dependencies = []

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "black>=22.0",
]

[project.urls]
"Homepage" = "https://github.com/treepoint/systeml"
"Bug Tracker" = "https://github.com/treepoint/systeml/issues"